<template>
  <div class="main">
    <div class="chl-header">
      <i class="fa fa-train fa-5x vibrate-1"></i>
      <div class="text">
        <span id="point">
          NEW CHALLENGE
          <br style="margin:0; padding: 0;">
          250 POINTS!
        </span>
      </div>
    </div>
    <div class="chl-share">
      <a href="#">
        Share Challenge <i class="fa fa-share"></i>
      </a>
    </div>
    <div class="chl-details">
      <h1>Trip Challenge</h1>
      <h2>Beat the time!</h2>
      <div class="route">
        Stasiun UI - Stasiun Sudirman
        <br>
        &lt; 42 minutes
      </div>
      <span style="color:#08d5ce;margin-top:30px;">view weather &amp; traffic condition</span>
      <div class="buttons">
        <div @click="updateTitle" style="margin:0; padding:0;">
          <router-link to="/app" class="uk-button uk-button-danger">DECLINE</router-link>
        </div>
        <div style="margin:0; padding:0;">
          <router-link to="/countdown" class="uk-button uk-button-success">ACCEPT</router-link>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  data () {
    return {
      cards: []
    }
  },
  methods: {
    updateTitle () {
      this.$emit('updateTitle', 'COMMUTE POINTS')
    }
  },
  created () {
    this.$emit('login', false)
  }
}
</script>

<style scoped>
.main {
  display: flex;
  flex-direction: column;
}
.chl-header {
  display: flex;
  flex-direction: row;
  justify-content: center;
  align-items: center;
  background-color: rgba(240, 240, 240, 0.5);
  /* color: rgba(20, 20, 20, 0.7); */
  color: red;
  padding-top: 2em;
  padding-bottom: 2em;
}
.chl-header .text {
  display: flex;
  align-items: center;
  justify-content: center;
  margin-left: 1em;
}
.chl-header .text section {
  margin: 0;
  display: flex;
  flex-direction: column;
  align-items: center;
}
.chl-header section span {
  margin: 0;
  color: gold;
}
.chl-header .text span#point {
  font-weight: bold;
  font-size: 1.6em;
  color: goldenrod;
  /* text-shadow: 0 0 1em grey; */
  margin-left: 0.3em;
}
.chl-header section span i {
  font-size: 1.6em;
  text-shadow: 0 0 1em yellow;
  margin: 0.1em;
}
.chl-share {
  text-align: right;
  box-shadow: 0px 5px 3px grey;
  padding: 0.5em;
  font-size: 1.3em;
  font-weight: bold;
}
.chl-details {
  padding: 0.5em;
  padding-top: 2em; 
  text-align: center;
}
.chl-details h1,h2 {
  margin: 0 0 0.5em 0;
}
.chl-details .route {
  margin: 0 1em 0 1em;
  border: 1px solid goldenrod;
  box-shadow: 0 0 10px gold;
  background-color: rgba(250, 233, 25, 0.5);
  font-size: 1.5em;
  font-weight: bold;
  color: black;
  text-align: center;
}
.chl-details .buttons div {
  margin: 0;
  padding: 0;
}
.chl-details .buttons {
  display: flex;
  align-items: center;
  justify-content: center;
  margin-top: 30px;
  margin-bottom: 30px;
}
.chl-details .buttons a {
  font-weight: bold;
  font-size: 1em;
  margin: 10px;
  box-shadow: 0 0 5px grey;
}
.chl-details .buttons a.uk-button-success {
  background-color: green;
  border: 1px solid green;
  color: white;
}
.vibrate-1 {
	-webkit-animation: vibrate-1 0.7s linear infinite both;
	        animation: vibrate-1 0.7s linear infinite both;
}
/* ----------------------------------------------
 * Generated by Animista on 2017-10-14 14:20:26
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation vibrate-1
 * ----------------------------------------
 */
@-webkit-keyframes vibrate-1 {
  0% {
    -webkit-transform: translate(0);
            transform: translate(0);
  }
  20% {
    -webkit-transform: translate(-2px, 2px);
            transform: translate(-2px, 2px);
  }
  40% {
    -webkit-transform: translate(-2px, -2px);
            transform: translate(-2px, -2px);
  }
  60% {
    -webkit-transform: translate(2px, 2px);
            transform: translate(2px, 2px);
  }
  80% {
    -webkit-transform: translate(2px, -2px);
            transform: translate(2px, -2px);
  }
  100% {
    -webkit-transform: translate(0);
            transform: translate(0);
  }
}
@keyframes vibrate-1 {
  0% {
    -webkit-transform: translate(0);
            transform: translate(0);
  }
  20% {
    -webkit-transform: translate(-2px, 2px);
            transform: translate(-2px, 2px);
  }
  40% {
    -webkit-transform: translate(-2px, -2px);
            transform: translate(-2px, -2px);
  }
  60% {
    -webkit-transform: translate(2px, 2px);
            transform: translate(2px, 2px);
  }
  80% {
    -webkit-transform: translate(2px, -2px);
            transform: translate(2px, -2px);
  }
  100% {
    -webkit-transform: translate(0);
            transform: translate(0);
  }
}
</style>
