<template>
  <div class="finished">
    <h1 class="uk-h1">Challenge Finished!</h1>
    <div class="dollar flip-vertical-right">
      <i class="fa fa-usd fa-5x"></i>
    </div>
    <h1 class="uk-h1 green">+350 Points</h1>
    <h2>Total points: 585</h2>
    <div class="media-social">
      <div class="icon facebook">
        <i class="fa fa-2x fa-facebook"></i>
      </div>
      <div class="icon whatsapp">
        <i class="fa fa-2x fa-whatsapp"></i>
      </div>
      <div class="icon instagram">
        <i class="fa fa-2x fa-instagram"></i>
      </div>
      <div class="icon twitter">
        <i class="fa fa-2x fa-twitter"></i>
      </div>
    </div>
    <button class="trade-point">
      TRADE MY POINT
    </button>
  </div>
</template>

<script>
export default {
  created () {
    this.$emit('login', false)
  }
}
</script>

<style scoped>
.finished {
  padding-top: 1em;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  text-align: center;
}
.finished .dollar {
  border: 10px solid gold;
  border-radius: 50%;
  height: 100px;
  width: 100px;
  display: flex;
  align-items: center;
  justify-content: center;
  color: transparent;
  background-color: gold;
  color: rgba(255, 255, 255, 1);
  box-shadow: 0 0 50px grey;
  margin-top:1em;
  z-index: 20;
}
.green {
  color: green;
}
.media-social {
  display: flex;
  align-items: center;
  justify-content: center;
}
.media-social .icon {
  width: 50px;
  height: 50px;
  color: white;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 50%;
  margin: 0.5em;
}
.facebook {
  background-color: #314b7e;
}
.whatsapp {
  background-color: #2fbf39;
}
.instagram {
  background-color: #3f60a5;
}
.twitter {
  background-color: #339dc4;
}
.trade-point {
  margin: 0.5em;
  padding: 0.5em;
  box-shadow: 0 0 10px grey;
  background-color: #00960c;
  border: 1px solid #00960c;
  border-radius: 5px;
  color: white;
  font-size: 2em;
}
h1 {
  margin: 0;
}
h2 {
  padding-top: 0;
  margin-top: 0;
  font-weight: bold;
}
.flip-vertical-right {
	-webkit-animation: flip-vertical-right 3s cubic-bezier(0.455, 0.030, 0.515, 0.955) infinite both;
	        animation: flip-vertical-right 3s cubic-bezier(0.455, 0.030, 0.515, 0.955) infinite both;
}
/* ----------------------------------------------
 * Generated by Animista on 2017-10-14 14:7:2
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation flip-vertical-right
 * ----------------------------------------
 */
@-webkit-keyframes flip-vertical-right {
  0% {
    -webkit-transform: rotateY(0);
            transform: rotateY(0);
  }
  100% {
    -webkit-transform: rotateY(360deg);
            transform: rotateY(360deg);
  }
}
@keyframes flip-vertical-right {
  0% {
    -webkit-transform: rotateY(0);
            transform: rotateY(0);
  }
  100% {
    -webkit-transform: rotateY(360deg);
            transform: rotateY(360deg);
  }
}
</style>
