<template>
<div class="main">
  <div class="carousel">
    <img src="../assets/commute-point.png" alt="">
    <div class="uk-position-relative uk-light" style="padding:1em; justify-contents:center;">
      <div class="uk-position-bottom-center uk-light">
        <ul class="uk-dotnav uk-flex-nowrap">
          <li class="uk-active"><a href="#">Item 1</a></li>
          <li><a href="#">Item 2</a></li>
          <li><a href="#">Item 3</a></li>
          <li><a href="#">Item 4</a></li>
          <li><a href="#">Item 5</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="features">
    <div class="content tap-out" @click="notify">
      <span uk-icon="icon: credit-card; ratio: 3;"></span>
      <p>
        TAP OUT
      </p>
    </div>
    <div class="content challenge" @click="updateChl">
      <router-link to="/challenge" style="text-decoration: none; color: white;">
        <span uk-icon="icon: clock; ratio: 3;"></span>
        <p style="font-size: 0.6em; word-wrap: break-word;">
          TRAVEL TIME<br>EXPERIENCE CHALLENGE
        </p>
      </router-link>
    </div>
    <div class="content share">
      <a class="twitter-share-button" 
      href="https://twitter.com/intent/tweet?text=I%20had%20a%20great%20commuting%20experience,%20beat%20my%20best%20time%20and%20get%20more%20points!&url=https://bit.ly/commute-points&hashtags=commutepoints,KRL,commuterline">
        <span uk-icon="icon: comment; ratio: 3;" style="color: white;"></span>
        <p style="font-size:0.8em; color:white;">
          SHARE MY TRIPS
        </p>
      </a>
    </div>
  </div>
  <div class="points">
    <div class="text">
      <h3>YOUR COMMUTE POINTS</h3>
    </div>
    <div class="dollar flip-vertical-right">
      <i class="fa fa-usd fa-5x"></i>
    </div>
    <div class="text">
      <h1>{{ points }} POINTS</h1>
    </div>
  </div>
</div>
</template>

<script>
export default {
  methods: {
    notify () {
      window.UIKit.notification({
        message: 'You just tapped +100 points',
        pos: 'top-right',
        timeout: 3000
      })
      this.points += 100
    },
    updateChl () {
      this.$emit('updateTitle', 'TRIP CHALLENGE')
    },
    test () {
      console.log('hahaha')
    }
  },
  data () {
    return {
      points: 235,
      images: [{
        id: 1,
        url: '/assets/commute-point.png'
      }]
    }
  },
  created () {
    this.$emit('login', false)
  }
}
</script>

<style scoped>
.main {
  display: flex;
  flex-direction: column;
  min-height: 700px;
}
.carousel {
  flex: 1 1 3em;
  padding: 1em;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-direction: column;
}
.features {
  flex: 0 1 7em;
  display: flex;
  justify-content: center;
}
.features .content {
  width: 33.333%;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-direction: column;
  text-align: center;
  color: white;
  font-weight: bold;
}
.features .content p {
  margin: 0;
}
.features .tap-out {
  background-color: #059886;
}
.features .challenge {
  background-color: #ffc603;
}
.features .share {
  background-color: #4f4f4f;
}
.points {
  flex: 1 1 auto;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  background: 
    radial-gradient(circle at 100% 50%, transparent 20%, rgba(255,255,255,.3) 21%, rgba(255,255,255,.3) 34%, transparent 35%, transparent),
    radial-gradient(circle at 0% 50%, transparent 20%, rgba(255,255,255,.3) 21%, rgba(255,255,255,.3) 34%, transparent 35%, transparent) 0 -50px;
    background-color: #2cbdac;
    background-size:75px 100px;
}
.points .dollar {
  border: 10px solid gold;
  border-radius: 50%;
  height: 100px;
  width: 100px;
  display: flex;
  align-items: center;
  justify-content: center;
  color: transparent;
  background-color: gold;
  color: rgba(255, 255, 255, 1);
  box-shadow: 0 0 50px grey;
  z-index: 20;
}
.points .text h1,h3 {
  color: white;
  font-weight: bold;
  margin: 0;
}
.uk-card {
  margin-bottom: 1em;
}
ul.uk-dotnav li a {
  background-color: grey;
  height: 10px;
  width: 10px;
}
ul.uk-dotnav li.uk-active a {
  background-color: rgba(5, 5, 5, 0.7);
  height: 10px;
  width: 10px;
}
.flip-vertical-right {
	-webkit-animation: flip-vertical-right 3s cubic-bezier(0.455, 0.030, 0.515, 0.955) infinite both;
	        animation: flip-vertical-right 3s cubic-bezier(0.455, 0.030, 0.515, 0.955) infinite both;
}
/* ----------------------------------------------
 * Generated by Animista on 2017-10-14 14:7:2
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation flip-vertical-right
 * ----------------------------------------
 */
@-webkit-keyframes flip-vertical-right {
  0% {
    -webkit-transform: rotateY(0);
            transform: rotateY(0);
  }
  100% {
    -webkit-transform: rotateY(360deg);
            transform: rotateY(360deg);
  }
}
@keyframes flip-vertical-right {
  0% {
    -webkit-transform: rotateY(0);
            transform: rotateY(0);
  }
  100% {
    -webkit-transform: rotateY(360deg);
            transform: rotateY(360deg);
  }
}
</style>
